### ISSUE TITLE
Progress log #1 ARCHIVED

### ISSUE THREAD

**Issue by andrewbluepiano** [nzenmods/website#1]
Hey, 
Connor asked me to spiff up ur code. Ima do it by putting it on my site under /nzen/ (/nzen/index.html) and will give you a zipped version when I am done.

**Comment by andrewbluepiano** [comment]
removing css from index and making seperate css file

**Comment by andrewbluepiano** [comment]
fixed code in header and added meta tags

**Comment by andrewbluepiano** [comment]
added browser specific customization tags to head

**Comment by cquick97** [comment]
This is basically just his list of changes as he does them. When done, he will give the code to me and I'll push to the repo.

**Comment by andrewbluepiano** [comment]
live changes at andrewswebsandbox.com/nzen/index.html

**Comment by andrewbluepiano** [comment]
Spry assets are sins in modern websites lol

**Comment by andrewbluepiano** [comment]
changed "Copyright" at bottom of site to &copy;

**Comment by andrewbluepiano** [comment]
beautifying index.html

**Comment by andrewbluepiano** [comment]
fixed doctype html. it is supposed to be capitalized

**Comment by andrewbluepiano** [comment]
changed logo target from _top or something to 'body'

**Comment by andrewbluepiano** [comment]
BR's?

**Comment by andrewbluepiano** [comment]
added paragraph declaration starting in line 86

**Comment by andrewbluepiano** [comment]
removed &nbsp; from paragraph, it is just a outdated method of cheating. and ultimately makes things degrate in css design

**Comment by andrewbluepiano** [comment]
put footer text in a paragraph decleration

**Comment by andrewbluepiano** [comment]
footer should not be a div, it is its own css class, and should be formatted as "<footer>". Fixing that. Index code has been beautified to a decent level

**Comment by andrewbluepiano** [comment]
- tried to say should be formatted as "footer" in brackets or whatever < these are called

**Comment by andrewbluepiano** [comment]
removed some text at head of css about utf-8. No idea where it came from, but saying the css is utf8 is not something you type into the css.... its automatic and also declared in the html

**Comment by andrewbluepiano** [comment]
beautifying css and commenting in issues

**Comment by andrewbluepiano** [comment]
src term used in css is invalid

**Comment by andrewbluepiano** [comment]
the spry css that is referenced in the html is not in github and is not on your web server. I am removing that line anyway as spry assets are a huge nono in modern web

**Comment by andrewbluepiano** [comment]
header css class needs to be added and css being used my nav bar needs to be redone under the header element

**Comment by andrewbluepiano** [comment]
css is not css3. A lot of terms need to be overhauled to css3 classes

**Comment by andrewbluepiano** [comment]
text align is outdated. Will be overhauled

**Comment by andrewbluepiano** [comment]
Basic css beautification completed. Going to add comments now to indicate stuffz

**Comment by andrewbluepiano** [comment]
http://www.css-validator.org/validator?uri=http%3A%2F%2Fandrewswebsandbox.com%2Fnzen%2Findex.html&profile=css21&usermedium=all&warning=1&lang=en

**Comment by andrewbluepiano** [comment]
textdecoration thing not needed once reset.css is implemented

**Comment by andrewbluepiano** [comment]
tons of stuff is needlessly repeated, and would have automatically been inherited by parent elements.

**Comment by andrewbluepiano** [comment]
two General css comments have been added to code

**Comment by andrewbluepiano** [comment]
Need to change sizes to max, min, and percents to begin conditional css establishement

**Comment by andrewbluepiano** [comment]
Finished additional round of commenting marking outdated, bad, good, and excessive css code sections

**Comment by andrewbluepiano** [comment]
getting error in firefox developer tools in regards to css linkage, but everything appears fine. Will investigate

**Comment by andrewbluepiano** [comment]
css classes need to be put in order in the file

**Comment by andrewbluepiano** [comment]
Leaving school. May do some more at home

**Comment by andrewbluepiano** [comment]
Starting up again. Reorganizing css

**Comment by andrewbluepiano** [comment]
Changed css file name to style.css

**Comment by andrewbluepiano** [comment]
fixed missing dev ender on backers page
beautifying and restructurizing backers page

**Comment by andrewbluepiano** [comment]
changing supporters list to ul list.

**Comment by andrewbluepiano** [comment]
backers.html initial cleaning done.

**Comment by andrewbluepiano** [comment]
enzen.html cleanup done. 
will be adding lightbox plugin to preorder page

**Comment by andrewbluepiano** [comment]
I need the video files so I can embed them in pages.

**Comment by andrewbluepiano** [comment]
Cleaned up.... whatever page that was.

**Comment by andrewbluepiano** [comment]
All the pages have had initial cleaning!!! If you look at them you will see some dont look right, thats because the code was so messed up and fragile that cleaning it tweaked stuff. Its all going to look bad though because I will most likely do a complete overhaul of the CSS instead of repairing whats there/

**Comment by andrewbluepiano** [comment]
Im going to sleep now

**Comment by andrewbluepiano** [comment]
Im back
Doing more work. Will implement the Lightbox plugin on all images now

**Comment by andrewbluepiano** [comment]
Adding some misc open source js files

**Comment by andrewbluepiano** [comment]
Navbar classes need to be restructured to li sub classes

**Comment by andrewbluepiano** [comment]
Lol realised why reset css wasnt working right, fixed it on homepage and am redesigning header linked files, about to distribute it site wide

**Comment by andrewbluepiano** [comment]
Removing all br tags to see what I need to work with

**Comment by andrewbluepiano** [comment]
Lightbox is working on home page. just click the image to see it

**Comment by andrewbluepiano** [comment]
div class container is never closed

**Comment by andrewbluepiano** [comment]
working on footer structure. overhauling its css

**Comment by andrewbluepiano** [comment]
Oh lord. Because of div elemtns being used for everything I can barely inspect the live site.

**Comment by andrewbluepiano** [comment]
headings need to be h tags

**Comment by andrewbluepiano** [comment]
changing site content width to 900px which is the standard. because sizes have been set using static pixel dimensions I will have to recalculate all the sizes to percentages and factor in margins, and padding

**Comment by andrewbluepiano** [comment]
changing color word values to correct hex values

**Comment by andrewbluepiano** [comment]
nav color blocks width changed to correct percentage from static pixel dimension

**Comment by andrewbluepiano** [comment]
changed colors to hex values, standardizing the order of css elements in classes

**Comment by andrewbluepiano** [comment]
removing text decoration elements from css. they are unneeded in the code that currently exists as the default value is already none

**Comment by andrewbluepiano** [comment]
removed underlines from links by using a global condition for the a tag with a no text decoration declaration

**Comment by andrewbluepiano** [comment]
Working on header

**Comment by andrewbluepiano** [comment]
I hate everything. Just spent at least 20 mins on a issue that shoulda taken 30 seconds

**Comment by andrewbluepiano** [comment]
Header is basically done in terms of initial code restructurization. I will tweak it after all code site wide in in a basic decent structure

**Comment by andrewbluepiano** [comment]
Working on footer

**Comment by andrewbluepiano** [comment]
Footer initial redo
